OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CrudOperations.Models
{
    public class Book
    {
        [Display(Name ="ID")]
        [Required]
        public int Id { get; set; }
        [Display(Name = "Isbn")]
        [Required]
        public string Isbn { get; set; }
        [Display(Name = "Title")]
        [Required]
        public string Title { get; set; }
        [Display(Name = "Publisher")]
        [Required]
        public string Publisher { get; set; }

        [Display(Name = "PublishDate")]
        [Required]
        public  string PublishDate { get; set; }

    }
}

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Models/BookViewModel.cs
using System;

using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CrudOperations.Models
{
    public class BookViewModel
    {
        public Book EditedBook { get; set; }

        public List<Book> ListOfBooks { get; set; }
    

    }
}

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using CrudOperations.Areas.HelpPage.ModelDescriptions;
using CrudOperations.Areas.HelpPage.Models;

namespace CrudOperations.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Controllers/BookController.cs
using AutoMapper;
using CrudOperations.Models;
using MyLibary.Data;
using MyLibary.Logic;
using MyLibary.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebSockets;

namespace CrudOperations.Controllers
{
    public class BookController : Controller
    {
        ILogic logic;
        IMapper mapper;
        BookViewModel vm;

        public BookController()
        {
            LibaryDatabaseEntities lb = new LibaryDatabaseEntities();
            Repository repo = new Repository(lb);
            logic = new LibaryLogic();
            mapper = MapperFactory.CreateMapper();

            vm = new BookViewModel();
            vm.EditedBook = new Book();
            var books = logic.GetAll();
            vm.ListOfBooks = mapper.Map<IList<Konyv>, List<Models.Book>>(books);
        }

        Book GetBook(int id)
        {
            Konyv oneBook = logic.GetOne(id);
            return mapper.Map<Konyv, Models.Book>(oneBook);
        }

        // GET: Book
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("BookIndex", vm);
        }

        // GET: Book/Details/5
        public ActionResult Details(int id)
        {
            return View("BookDetails", GetBook(id));
        }

        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete Fail";
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedBook = GetBook(id);
            return View("BookIndex", vm);
        }

        [HttpPost]
        public ActionResult Edit(Book book, string editAction)
        {
            if (ModelState.IsValid && book != null)
            {
                TempData["editResult"] = "Edit OK";
                if (editAction == "AddNew")
                {
                    Konyv k = new Konyv { Cim = book.Title, ISBN = book.Isbn, Kiado = book.Publisher };
                    
                    logic.AddBook(k);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["editAction"] = "Edit";
                vm.EditedBook = book;
                return View("BookIndex", vm);

            }
        }

    }
}

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Views/Book/BookDetails.cshtml
@model CrudOperations.Models.Book
@{
    ViewBag.Title = "BookDetails";
}

<h2>BookDetails</h2>

@Html.ActionLink("Back to the list", "Index");

<table>
    <tr>
        <td>The Id for the car</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Title)</td>
        <td>@Html.DisplayFor(x => x.Title)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Isbn)</td>
        <td>@Html.DisplayFor(x => x.Isbn)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Supply)</td>
        <td>@Html.DisplayFor(x => x.Supply)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.PublishDate)</td>
        <td>@Html.DisplayFor(x => x.PublishDate)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.Publisher)</td>
        <td>@Html.DisplayFor(x => x.Publisher)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(x => x.FreeBook)</td>
        <td>@Html.DisplayFor(x => x.FreeBook)</td>
    </tr>
</table>

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Views/Book/BookEdited.cshtml
@model CrudOperations.Models.Book

<h2>Edit one book</h2>

@using (Html.BeginForm("Edit", "Book"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(x => x.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());

    <div class="editor-label">@Html.LabelFor(x => x.Title)</div>
    <div class="editor-filed">@Html.EditorFor(x => x.Title)</div>

    <div class="editor-label">@Html.LabelFor(x => x.PublishDate)</div>
    <div class="editor-filed">@Html.EditorFor(x => x.PublishDate)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Publisher)</div>
    <div class="editor-filed">@Html.EditorFor(x => x.Publisher)</div>

    <div class="editor-label">@Html.LabelFor(x => x.Supply)</div>
    <div class="editor-filed">@Html.EditorFor(x => x.Supply)</div>

    <div class="editor-label">@Html.LabelFor(x => x.FreeBook)</div>
    <div class="editor-filed">@Html.EditorFor(x => x.Isbn)</div>

    <input type="submit" value="send" />

}

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Views/Book/BookIndex.cshtml
@model CrudOperations.Models.BookViewModel
@{
    ViewBag.Title = "BookIndex";
}

<h2>Books Index</h2>

<p style="color:red; font-weight:bold">@TempData["editResult"]</p>
@Html.Partial("BookEdited", Model.EditedBook) 
@Html.Partial("BookList", Model.ListOfBooks)

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Views/Book/BookList.cshtml
@model IEnumerable<CrudOperations.Models.Book>

@{
    ViewBag.Title = "BookList";
}

<h2>BookList</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!!!</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Title)</th>
            <th>@Html.DisplayNameFor(m => m.First().Publisher)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Title)</td>
                <td>@Html.DisplayFor(m => item.Publisher)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}

OENIK_PROG3_2019_2_FLK8LL/CrudOperations/Views/Book/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>